"use client";

import { useMemo, useState } from "react";

type TermUnit = "years" | "months";
type Timing = "beginning" | "end";
type ScheduleMode = "yearly" | "monthly";
type Row = { month: number; year: number; contribution: number; interest: number; balance: number; totalContributions: number };
const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const percent = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });
const safe = (value: string) => { const number = Number(value); return Number.isFinite(number) && number > 0 ? number : 0; };

export default function CompoundInterestCalculatorClient() {
  const [principal, setPrincipal] = useState("10000"); const [rate, setRate] = useState("5"); const [term, setTerm] = useState("10"); const [termUnit, setTermUnit] = useState<TermUnit>("years");
  const [compound, setCompound] = useState("12"); const [contribution, setContribution] = useState("200"); const [contributionFrequency, setContributionFrequency] = useState("12");
  const [timing, setTiming] = useState<Timing>("end"); const [annualIncrease, setAnnualIncrease] = useState("0"); const [mode, setMode] = useState<ScheduleMode>("yearly"); const [copied, setCopied] = useState(false);

  const result = useMemo(() => {
    const starting = safe(principal); const annualRate = safe(rate) / 100; const months = Math.max(0, Math.round(termUnit === "years" ? safe(term) * 12 : safe(term)));
    const compounds = Math.max(1, safe(compound)); const contributionsPerYear = Math.max(1, safe(contributionFrequency)); const baseContribution = safe(contribution); const increase = safe(annualIncrease) / 100;
    const monthlyRate = annualRate ? (1 + annualRate / compounds) ** (compounds / 12) - 1 : 0; let balance = starting; let totalContributions = starting; let totalInterest = 0; const rows: Row[] = [];
    for (let month = 1; month <= months; month += 1) {
      const yearIndex = Math.floor((month - 1) / 12); const currentContribution = baseContribution * (1 + increase) ** yearIndex;
      const interval = 12 / contributionsPerYear; const contributionDue = Math.abs(month / interval - Math.round(month / interval)) < 1e-8;
      let deposited = 0;
      if (contributionDue && timing === "beginning") { balance += currentContribution; totalContributions += currentContribution; deposited = currentContribution; }
      const interest = balance * monthlyRate; balance += interest; totalInterest += interest;
      if (contributionDue && timing === "end") { balance += currentContribution; totalContributions += currentContribution; deposited = currentContribution; }
      rows.push({ month, year: Math.ceil(month / 12), contribution: deposited, interest, balance, totalContributions });
    }
    return { starting, annualRate, months, rows, futureBalance: balance, totalContributions, recurringContributions: totalContributions - starting, totalInterest, interestShare: balance > 0 ? totalInterest / balance * 100 : 0 };
  }, [principal, rate, term, termUnit, compound, contribution, contributionFrequency, timing, annualIncrease]);

  const yearly = useMemo(() => { const groups = new Map<number, Row[]>(); result.rows.forEach((row) => groups.set(row.year, [...(groups.get(row.year) ?? []), row])); return [...groups.entries()].map(([year, rows]) => ({ year, contributions: rows.reduce((sum, row) => sum + row.contribution, 0), interest: rows.reduce((sum, row) => sum + row.interest, 0), balance: rows.at(-1)?.balance ?? 0 })); }, [result.rows]);
  const valid = result.months > 0;
  async function copyResults() { await navigator.clipboard.writeText(["Numeravo Compound Interest Calculator", `Starting principal: ${usd.format(result.starting)}`, `Annual rate: ${percent.format(result.annualRate * 100)}%`, `Future balance: ${usd.format(result.futureBalance)}`, `Recurring contributions: ${usd.format(result.recurringContributions)}`, `Total interest earned: ${usd.format(result.totalInterest)}`].join("\n")); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  function csv() { const header = "Month,Year,Contribution,Interest,Balance,Total contributions"; const lines = result.rows.map((row) => [row.month, row.year, row.contribution.toFixed(2), row.interest.toFixed(2), row.balance.toFixed(2), row.totalContributions.toFixed(2)].join(",")); const blob = new Blob([[header, ...lines].join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "numeravo-compound-interest-growth.csv"; link.click(); URL.revokeObjectURL(url); }
  function reset() { setPrincipal("10000"); setRate("5"); setTerm("10"); setTermUnit("years"); setCompound("12"); setContribution("200"); setContributionFrequency("12"); setTiming("end"); setAnnualIncrease("0"); }

  return <section className="grid min-w-0 gap-6 lg:grid-cols-[minmax(0,.92fr)_minmax(0,1.08fr)]">
    <div className="min-w-0 rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8"><div className="flex justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#22C55E]">Growth assumptions</p><h2 className="mt-2 text-2xl font-bold">Estimate compound growth</h2></div><button type="button" onClick={reset} className="text-sm font-semibold text-[#A0AEC0] hover:text-white">Reset</button></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Starting principal" value={principal} set={setPrincipal} prefix="$"/><Field label="Annual interest rate" value={rate} set={setRate} suffix="%"/><label><span className="text-sm text-[#A0AEC0]">Time period</span><div className="mt-2 flex overflow-hidden rounded-xl border border-[#1F2937] bg-[#0B0F19] focus-within:border-[#22C55E]"><input aria-label="Time period" type="number" min="1" step="1" value={term} onChange={(e) => setTerm(e.target.value)} className="min-w-0 flex-1 bg-transparent px-4 py-3 outline-none"/><select aria-label="Time unit" value={termUnit} onChange={(e) => setTermUnit(e.target.value as TermUnit)} className="border-l border-[#1F2937] bg-[#0B0F19] px-3"><option value="years">years</option><option value="months">months</option></select></div></label><Select label="Compounding frequency" value={compound} set={setCompound} options={[["365","Daily"],["12","Monthly"],["4","Quarterly"],["2","Semiannually"],["1","Annually"]]}/><Field label="Regular contribution" value={contribution} set={setContribution} prefix="$"/><Select label="Contribution frequency" value={contributionFrequency} set={setContributionFrequency} options={[["12","Monthly"],["4","Quarterly"],["1","Annually"]]}/><Select label="Contribution timing" value={timing} set={(value) => setTiming(value as Timing)} options={[["end","End of period"],["beginning","Beginning of period"]]}/><Field label="Annual contribution increase" value={annualIncrease} set={setAnnualIncrease} suffix="%"/></div><p className="mt-6 text-xs leading-5 text-[#718096]">This projection assumes a consistent nominal annual rate and regular contributions. It does not model taxes, fees, inflation, market losses, or changing rates.</p></div>
    <div className="min-w-0 rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8" aria-live="polite"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#22C55E]">Estimated result</p>{!valid ? <p className="mt-6 text-[#A0AEC0]">Enter a time period greater than zero.</p> : <><p className="mt-4 text-sm text-[#A0AEC0]">Future balance</p><p className="mt-1 text-4xl font-bold">{usd.format(result.futureBalance)}</p><div className="mt-7 grid grid-cols-2 gap-3"><Card label="Starting principal" value={usd.format(result.starting)}/><Card label="Recurring contributions" value={usd.format(result.recurringContributions)}/><Card label="Total contributions" value={usd.format(result.totalContributions)}/><Card label="Interest earned" value={usd.format(result.totalInterest)}/></div><div className="mt-5 rounded-2xl border border-[#14532D] bg-[#052E16]/40 p-5 text-sm leading-6 text-[#BBF7D0]">Estimated interest represents <strong>{percent.format(result.interestShare)}%</strong> of the projected future balance.</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button type="button" onClick={copyResults} className="rounded-xl bg-[#22C55E] px-4 py-3 font-semibold text-[#07120A]">{copied ? "Copied" : "Copy results"}</button><button type="button" onClick={csv} className="rounded-xl border border-[#374151] px-4 py-3 font-semibold hover:border-[#22C55E]">Download CSV</button></div></>}</div>
    {valid && <div className="min-w-0 rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#22C55E]">Growth schedule</p><h2 className="mt-2 text-2xl font-bold">Contributions and compound interest</h2></div><div className="flex rounded-xl border border-[#1F2937] p-1"><Toggle active={mode === "yearly"} click={() => setMode("yearly")}>Yearly</Toggle><Toggle active={mode === "monthly"} click={() => setMode("monthly")}>Monthly</Toggle></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-[#374151] text-[#A0AEC0]"><tr>{mode === "yearly" ? <><Th>Year</Th><Th>Contributions</Th><Th>Interest</Th><Th>Ending balance</Th></> : <><Th>Month</Th><Th>Contribution</Th><Th>Interest</Th><Th>Total contributions</Th><Th>Balance</Th></>}</tr></thead><tbody>{mode === "yearly" ? yearly.map((row) => <tr key={row.year} className="border-b border-[#1F2937]"><Td>{row.year}</Td><Td>{usd.format(row.contributions)}</Td><Td>{usd.format(row.interest)}</Td><Td>{usd.format(row.balance)}</Td></tr>) : result.rows.map((row) => <tr key={row.month} className="border-b border-[#1F2937]"><Td>{row.month}</Td><Td>{usd.format(row.contribution)}</Td><Td>{usd.format(row.interest)}</Td><Td>{usd.format(row.totalContributions)}</Td><Td>{usd.format(row.balance)}</Td></tr>)}</tbody></table></div></div>}
  </section>;
}

function Field({ label, value, set, prefix, suffix }: { label: string; value: string; set: (value: string) => void; prefix?: string; suffix?: string }) { return <label><span className="text-sm text-[#A0AEC0]">{label}</span><div className="mt-2 flex rounded-xl border border-[#1F2937] bg-[#0B0F19] focus-within:border-[#22C55E]">{prefix && <span className="px-3 py-3 text-[#A0AEC0]">{prefix}</span>}<input aria-label={label} type="number" min="0" step="any" value={value} onChange={(e) => set(e.target.value)} className="min-w-0 flex-1 bg-transparent px-3 py-3 outline-none"/>{suffix && <span className="px-3 py-3 text-[#A0AEC0]">{suffix}</span>}</div></label>; }
function Select({ label, value, set, options }: { label: string; value: string; set: (value: string) => void; options: string[][] }) { return <label><span className="text-sm text-[#A0AEC0]">{label}</span><select value={value} onChange={(e) => set(e.target.value)} className="mt-2 w-full rounded-xl border border-[#1F2937] bg-[#0B0F19] px-4 py-3 outline-none focus:border-[#22C55E]">{options.map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>; }
function Card({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#1F2937] bg-[#0B0F19] p-4"><p className="text-xs text-[#A0AEC0]">{label}</p><p className="mt-2 font-bold">{value}</p></div>; }
function Toggle({ active, click, children }: { active: boolean; click: () => void; children: React.ReactNode }) { return <button type="button" onClick={click} className={`rounded-lg px-4 py-2 text-sm font-semibold ${active ? "bg-[#22C55E] text-[#07120A]" : "text-[#A0AEC0]"}`}>{children}</button>; }
function Th({ children }: { children: React.ReactNode }) { return <th className="px-3 py-3 font-medium">{children}</th>; } function Td({ children }: { children: React.ReactNode }) { return <td className="px-3 py-3">{children}</td>; }
