import Link from "next/link";
import MortgageCalculatorClient from "./MortgageCalculatorClient";

import CalculatorCanvas from "@/components/calculators/CalculatorCanvas";
const url = "https://numeravo.com/finance/mortgage-calculator";
export const metadata = { title: "Mortgage Calculator: Monthly Payment, PMI & Taxes", description: "Estimate your mortgage payment with principal, interest, property taxes, home insurance, HOA dues, PMI, extra payments, and an amortization schedule.", alternates: { canonical: url }, openGraph: { title: "Mortgage Calculator: Payment, PMI & Taxes", description: "Calculate a complete estimated monthly mortgage payment and compare extra-payment savings.", url, siteName: "Numeravo", type: "website" }, twitter: { card: "summary_large_image", title: "Mortgage Calculator | Numeravo", description: "Estimate principal, interest, taxes, insurance, HOA dues, PMI, and payoff time." } };
const faqs = [
  { question: "What costs are included in a monthly mortgage payment?", answer: "A complete housing-payment estimate may include mortgage principal and interest, property taxes, homeowners insurance, HOA dues, and private mortgage insurance. Lender and property-specific charges may add other costs." },
  { question: "How is mortgage principal and interest calculated?", answer: "A fixed-rate mortgage uses the loan amount, monthly interest rate, and total number of monthly payments to calculate an amortized principal-and-interest payment." },
  { question: "When is private mortgage insurance required?", answer: "PMI is commonly associated with conventional mortgages where the down payment is below 20%, but requirements and cancellation rules depend on the lender, loan program, payment history, and property value." },
  { question: "Do extra mortgage payments reduce interest?", answer: "Extra principal payments can reduce the balance sooner, potentially shortening the payoff period and reducing interest. Confirm how the servicer applies extra funds and whether any prepayment restriction exists." },
  { question: "Are property taxes and insurance fixed for the entire mortgage?", answer: "No. Taxes, insurance premiums, HOA dues, and PMI can change independently of a fixed mortgage rate, so the complete housing payment may change over time." },
  { question: "Why might a lender quote differ from this calculator?", answer: "Lenders may use different payment dates, rounding, escrow estimates, insurance figures, PMI pricing, fees, loan programs, or underwriting assumptions." },
];
const schemas = [{ "@context": "https://schema.org", "@type": "WebApplication", name: "Numeravo Mortgage Calculator", url, description: metadata.description, applicationCategory: "FinanceApplication", operatingSystem: "Any", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, featureList: ["Complete mortgage payment estimate", "PMI estimate", "Extra-payment comparison", "Amortization schedule", "CSV export"] }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Finance Calculators", item: "https://numeravo.com/finance" }, { "@type": "ListItem", position: 2, name: "Mortgage Calculator", item: url }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((f) => ({ "@type": "Question", name: f.question, acceptedAnswer: { "@type": "Answer", text: f.answer } })) }];

export default function MortgageCalculatorPage() { return <CalculatorCanvas theme="finance" className="px-6 py-12">{schemas.map((schema, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }}/>) }<div className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="text-sm text-[#A0AEC0]"><Link href="/finance" className="hover:text-[#22C55E]">Finance Calculators</Link><span className="mx-2">/</span><span className="text-white">Mortgage Calculator</span></nav><header className="mt-8 max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[.25em] text-[#22C55E]">Finance calculator</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Mortgage Calculator</h1><p className="mt-6 text-lg leading-8 text-[#A0AEC0]">Estimate your complete monthly mortgage payment, including principal and interest, property taxes, homeowners insurance, HOA dues, and PMI. Compare extra payments and review the amortization schedule.</p></header><div className="mt-10"><MortgageCalculatorClient/></div>
  <section className="mt-14 grid gap-6 md:grid-cols-3"><Info title="Complete payment estimate">See the initial estimated housing payment—not only principal and interest.</Info><Info title="Calculation method">Uses standard fixed-rate monthly amortization and applies extra payments directly to principal.</Info><Info title="Planning limitation">This estimate is not a lender quote or affordability approval. Actual escrow and loan costs can change.</Info></section>
  <Content title="How to use the mortgage calculator">Enter the home price and down payment, followed by the fixed interest rate and loan term. Add annual property taxes and insurance, monthly HOA dues, an estimated PMI rate, closing costs, and any optional extra principal payment. Results update automatically.</Content>
  <Content title="What is included in the mortgage payment?">Principal repays the amount borrowed, while interest is the lender’s charge for financing. Property taxes, homeowners insurance, HOA dues, and PMI are separate housing expenses. The calculator combines their monthly estimates to show a more complete initial payment.</Content>
  <Content title="Down payments, loan amount, and cash needed">The loan amount equals the home price minus the entered down payment. Estimated cash needed combines the down payment and closing costs. It does not include every possible prepaid item, escrow deposit, inspection, moving expense, or lender reserve requirement.</Content>
  <Content title="PMI and loan-to-value assumptions">This calculator estimates PMI when the scheduled beginning loan balance exceeds 80% of the original home price. Real PMI eligibility, price, removal date, and cancellation process depend on the mortgage program, lender, property value, and applicable rules.</Content>
  <Content title="How extra payments affect a mortgage">Additional principal reduces the outstanding balance sooner and may reduce future interest and the payoff period. It does not normally reduce taxes, insurance, or HOA dues. Confirm that the servicer applies additional money to principal.</Content>
  <section className="mt-14 rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8"><h2 className="text-2xl font-bold">Mortgage calculator FAQs</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{faqs.map((f) => <article key={f.question} className="rounded-2xl border border-[#1F2937] bg-[#0B0F19] p-5"><h3 className="font-semibold">{f.question}</h3><p className="mt-3 text-sm leading-6 text-[#A0AEC0]">{f.answer}</p></article>)}</div></section>
  <section className="mt-10 rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8"><h2 className="text-2xl font-bold">Methodology and disclaimer</h2><p className="mt-4 leading-7 text-[#A0AEC0]">Numeravo uses the supplied inputs and a standard fixed-rate monthly amortization model. Estimates are for educational planning only and are not financial, lending, tax, legal, or real-estate advice. Confirm rates, APR, fees, escrow, PMI, insurance, taxes, and payment terms with qualified professionals and the lender.</p><p className="mt-4 text-sm text-[#718096]">Created and maintained by Numeravo Technologies LLC.</p></section>
  <section className="mt-10 rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8"><h2 className="text-2xl font-bold">Related finance calculators</h2><div className="mt-5 flex flex-wrap gap-3"><Link href="/finance/savings-calculator" className="rounded-xl border border-[#374151] px-5 py-3 font-semibold hover:border-[#22C55E]">Savings Calculator</Link><Link href="/finance/credit-card-payoff-calculator" className="rounded-xl border border-[#374151] px-5 py-3 font-semibold hover:border-[#22C55E]">Credit Card Payoff Calculator</Link><Link href="/finance/auto-loan-calculator" className="rounded-xl border border-[#374151] px-5 py-3 font-semibold hover:border-[#22C55E]">Auto Loan Calculator</Link><Link href="/finance/compound-interest-calculator" className="rounded-xl border border-[#374151] px-5 py-3 font-semibold hover:border-[#22C55E]">Compound Interest Calculator</Link><Link href="/finance/loan-calculator" className="rounded-xl border border-[#374151] px-5 py-3 font-semibold hover:border-[#22C55E]">Loan Calculator</Link><Link href="/finance" className="rounded-xl border border-[#374151] px-5 py-3 font-semibold hover:border-[#22C55E]">All Finance Calculators</Link></div></section></div></CalculatorCanvas>; }
function Info({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-2xl border border-[#1F2937] bg-[#121826] p-5"><h2 className="font-semibold text-[#4ADE80]">{title}</h2><p className="mt-3 text-sm leading-6 text-[#A0AEC0]">{children}</p></article>; }
function Content({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-12 max-w-4xl"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-4 leading-7 text-[#A0AEC0]">{children}</p></section>; }
