"use client";
import { useMemo, useState } from "react";
import {
  calculateAllowableCost,
  calculateBreakEvenPrice,
  calculateProfitMarginMetrics,
  calculateTargetSellingPrice,
} from "@/lib/calculations/profitMargin";
type Mode = "margin" | "price" | "cost";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });
const pct = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });
const n = (v: string) => Math.max(0, Number(v) || 0);
export default function ProfitMarginCalculatorClient() {
  const [mode, setMode] = useState<Mode>("margin"); const [cost, setCost] = useState("40"); const [price, setPrice] = useState("75"); const [target, setTarget] = useState("35"); const [quantity, setQuantity] = useState("100"); const [fixedFee, setFixedFee] = useState("0"); const [feeRate, setFeeRate] = useState("0"); const [discount, setDiscount] = useState("15"); const [advanced, setAdvanced] = useState(false); const [copied, setCopied] = useState(false);
  const result = useMemo(() => { const c=n(cost),p=n(price),t=n(target),f=n(fixedFee),r=n(feeRate),q=n(quantity),d=Math.min(100,n(discount)); const invalidTarget=mode!=="margin"&&(t>=100||t+r>=100); let finalCost=c,finalPrice=p; if(!invalidTarget&&mode==="price") finalPrice=calculateTargetSellingPrice(c,t,f,r); if(!invalidTarget&&mode==="cost") finalCost=calculateAllowableCost(p,t,f,r); const base=calculateProfitMarginMetrics(finalCost,finalPrice,f,r); const breakEven=calculateBreakEvenPrice(finalCost,f,r); const discounted=calculateProfitMarginMetrics(finalCost,finalPrice*(1-d/100),f,r); const maxDiscount=finalPrice>0&&breakEven!==null?Math.max(0,Math.min(100,(1-breakEven/finalPrice)*100)):0; return {...base,q,invalidTarget,breakEven,discount:d,discounted,maxDiscount,revenue:finalPrice*q,totalCost:finalCost*q,totalFees:base.fees*q,totalProfit:base.profitAfterFees*q}; },[mode,cost,price,target,quantity,fixedFee,feeRate,discount]);
  const reset=()=>{setMode("margin");setCost("40");setPrice("75");setTarget("35");setQuantity("100");setFixedFee("0");setFeeRate("0");setDiscount("15");setAdvanced(false);};
  async function copy(){await navigator.clipboard.writeText(["Numeravo Profit Margin Calculator",`Selling price: ${money.format(result.price)}`,`Unit cost: ${money.format(result.cost)}`,`Gross profit: ${money.format(result.grossProfit)}`,`Gross margin: ${pct.format(result.grossMargin)}%`,`Markup: ${result.markup===null?"N/A":`${pct.format(result.markup)}%`}`,`Profit after fees: ${money.format(result.profitAfterFees)}`,`Margin after fees: ${pct.format(result.marginAfterFees)}%`,`Break-even price: ${result.breakEven===null?"N/A":money.format(result.breakEven)}`].join("\n"));setCopied(true);window.setTimeout(()=>setCopied(false),1600);}
  function csv(){const text=["Metric,Value",`Selling price,${result.price.toFixed(2)}`,`Unit cost,${result.cost.toFixed(2)}`,`Gross profit,${result.grossProfit.toFixed(2)}`,`Gross margin,${result.grossMargin.toFixed(2)}%`,`Markup,${result.markup?.toFixed(2)??"N/A"}`,`Transaction fees,${result.fees.toFixed(2)}`,`Profit after fees,${result.profitAfterFees.toFixed(2)}`,`Margin after fees,${result.marginAfterFees.toFixed(2)}%`,`Break-even price,${result.breakEven?.toFixed(2)??"N/A"}`,`Quantity,${result.q}`,`Total profit,${result.totalProfit.toFixed(2)}`].join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="numeravo-profit-margin-results.csv";a.click();URL.revokeObjectURL(url);}
  const invalidBase=mode==="margin"&&result.price<=0;
  return <section className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
    <div className="rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8"><div className="grid gap-1 rounded-xl bg-[#0B0F19] p-1 sm:grid-cols-3"><ModeButton active={mode==="margin"} onClick={()=>setMode("margin")}>Calculate margin</ModeButton><ModeButton active={mode==="price"} onClick={()=>setMode("price")}>Find selling price</ModeButton><ModeButton active={mode==="cost"} onClick={()=>setMode("cost")}>Find allowable cost</ModeButton></div><div className="mt-7 grid gap-5 sm:grid-cols-2">{mode!=="cost"&&<Input label="Cost per unit" help="Direct cost to buy, produce, or deliver one unit." value={cost} set={setCost} prefix="$"/>}{mode!=="price"&&<Input label="Selling price per unit" help="Amount collected before sales tax." value={price} set={setPrice} prefix="$"/>}{mode!=="margin"&&<Input label="Target profit margin" help="Desired profit as a percentage of selling price." value={target} set={setTarget} suffix="%"/>}<Input label="Quantity" help="Number of units in the totals estimate." value={quantity} set={setQuantity} suffix="units"/></div><button type="button" onClick={()=>setAdvanced(v=>!v)} className="mt-6 text-sm font-semibold text-[#22D3EE]">{advanced?"Hide":"Show"} transaction fees</button>{advanced&&<div className="mt-5 grid gap-5 sm:grid-cols-2"><Input label="Fixed fee per unit" help="Flat fee charged on each transaction." value={fixedFee} set={setFixedFee} prefix="$"/><Input label="Percentage fee" help="Fee calculated from the selling price." value={feeRate} set={setFeeRate} suffix="%"/></div>}{result.invalidTarget&&<div className="mt-5 rounded-xl border border-red-900 bg-red-950/40 p-4 text-sm text-red-300">Target margin plus percentage fees must be less than 100%. Reduce the target margin or fee percentage.</div>}{invalidBase&&<div className="mt-5 rounded-xl border border-red-900 bg-red-950/40 p-4 text-sm text-red-300">Selling price must be greater than zero to calculate a margin.</div>}<button type="button" onClick={reset} className="mt-6 rounded-xl border border-[#374151] px-5 py-3 text-sm font-semibold hover:border-[#06B6D4]">Reset calculator</button><p className="mt-6 text-xs leading-5 text-[#718096]">Sales tax, income tax, overhead, returns, discounts, shipping, and other expenses are excluded unless included in your inputs.</p></div>
    <div className="rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8" aria-live="polite"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#06B6D4]">Estimated result</p><p className="mt-5 text-sm text-[#A0AEC0]">{mode==="price"?"Required selling price":mode==="cost"?"Maximum allowable cost":"Gross profit margin"}</p><p className={`mt-1 text-4xl font-bold ${result.profitAfterFees<0?"text-red-400":""}`}>{result.invalidTarget?"—":mode==="price"?money.format(result.price):mode==="cost"?money.format(result.cost):`${pct.format(result.grossMargin)}%`}</p>{!result.invalidTarget&&!invalidBase&&<p className="mt-3 text-sm leading-6 text-[#A0AEC0]">At {money.format(result.price)} per unit with {money.format(result.cost)} of direct cost, gross profit is {money.format(result.grossProfit)} per unit. That is a {pct.format(result.grossMargin)}% margin{result.markup===null?"":` and ${pct.format(result.markup)}% markup`}.</p>}{result.profitAfterFees<0&&<p className="mt-3 rounded-xl border border-red-900 bg-red-950/40 p-3 text-sm text-red-300">The selling price does not cover cost and entered transaction fees.</p>}<div className="mt-7 grid grid-cols-2 gap-3"><Card label="Gross profit per unit" value={money.format(result.grossProfit)}/><Card label="Gross margin" value={`${pct.format(result.grossMargin)}%`}/><Card label="Markup on cost" value={result.markup===null?"Not applicable":`${pct.format(result.markup)}%`}/><Card label="Revenue multiplier" value={result.multiplier===null?"Not applicable":`${pct.format(result.multiplier)}×`}/><Card label="Transaction fees" value={money.format(result.fees)}/><Card label="Profit after fees" value={money.format(result.profitAfterFees)}/><Card label="Margin after fees" value={`${pct.format(result.marginAfterFees)}%`}/><Card label="Break-even price" value={result.breakEven===null?"Not available":money.format(result.breakEven)}/></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={copy} disabled={result.invalidTarget} className="rounded-xl bg-[#06B6D4] px-4 py-3 font-semibold text-[#042F3A] disabled:opacity-50">{copied?"Copied":"Copy results"}</button><button onClick={csv} disabled={result.invalidTarget} className="rounded-xl border border-[#374151] px-4 py-3 font-semibold hover:border-[#06B6D4] disabled:opacity-50">Download CSV</button></div></div>
    <div className="rounded-3xl border border-[#1F2937] bg-[#121826] p-6 md:p-8 lg:col-span-2"><h2 className="text-2xl font-bold">Margin, markup, and selling price</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><Explain title="Profit margin">Profit divided by selling price. It answers: “What percentage of each sales dollar is profit?”</Explain><Explain title="Markup">Profit divided by cost. It answers: “How much was added above cost?” Markup is not the same percentage as margin.</Explain><Explain title="Selling price">The amount charged to the customer before sales tax. It must cover cost, fees, and the desired profit.</Explain></div><h2 className="mt-10 text-2xl font-bold">Totals for {pct.format(result.q)} units</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Total revenue" value={money.format(result.revenue)}/><Card label="Total direct cost" value={money.format(result.totalCost)}/><Card label="Total fees" value={money.format(result.totalFees)}/><Card label="Profit after fees" value={money.format(result.totalProfit)}/></div><div className="mt-10 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="text-2xl font-bold">Test a discount</h2><div className="mt-5"><Input label="Discount" help="Percentage removed from the current selling price." value={discount} set={setDiscount} suffix="%"/></div><p className="mt-4 text-sm text-[#A0AEC0]">Maximum estimated discount before a loss: <strong className="text-white">{pct.format(result.maxDiscount)}%</strong></p></div><div className="grid gap-3 sm:grid-cols-2"><Card label="Discounted price" value={money.format(result.discounted.price)}/><Card label="Profit after fees" value={money.format(result.discounted.profitAfterFees)}/><Card label="Gross margin" value={`${pct.format(result.discounted.grossMargin)}%`}/><Card label="Margin after fees" value={`${pct.format(result.discounted.marginAfterFees)}%`}/></div></div>{result.discounted.profitAfterFees<0&&<p className="mt-5 rounded-xl border border-red-900 bg-red-950/40 p-4 text-sm text-red-300">This discount produces an estimated loss after the entered cost and fees.</p>}</div>
  </section>;
}
function Input({label,help,value,set,prefix,suffix}:{label:string;help?:string;value:string;set:(v:string)=>void;prefix?:string;suffix?:string}){return <label><span className="text-sm text-[#A0AEC0]">{label}</span>{help&&<span className="mt-1 block text-xs text-[#718096]">{help}</span>}<div className="mt-2 flex rounded-xl border border-[#1F2937] bg-[#0B0F19] focus-within:border-[#06B6D4]">{prefix&&<span className="px-3 py-3 text-[#A0AEC0]">{prefix}</span>}<input type="number" min="0" step="any" value={value} onChange={e=>set(e.target.value)} className="min-w-0 flex-1 bg-transparent px-3 py-3 outline-none"/>{suffix&&<span className="px-3 py-3 text-sm text-[#A0AEC0]">{suffix}</span>}</div></label>;}
function ModeButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" onClick={onClick} className={`rounded-lg px-3 py-3 text-sm font-semibold ${active?"bg-[#06B6D4] text-[#042F3A]":"text-[#A0AEC0]"}`}>{children}</button>;}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#1F2937] bg-[#0B0F19] p-4"><p className="text-xs text-[#A0AEC0]">{label}</p><p className="mt-1 font-bold">{value}</p></div>;}
function Explain({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-2xl border border-[#1F2937] bg-[#0B0F19] p-5"><h3 className="font-semibold text-[#22D3EE]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#A0AEC0]">{children}</p></article>;}
